name: .v/.sv Linting

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Verilator
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator

      - name: Run Verilator Strict Lint
        shell: bash
        run: |
          echo "Running Verilator lint..."
          status=0

          while IFS= read -r file; do
            echo "Linting: $file"

            verilator --lint-only "$file"

            if [ $? -ne 0 ]; then
              status=1
            fi
          done < <(
            find SRC -type f \( -name "*.v" -o -name "*.sv" \) \
              ! -name "*_tb.v" \
              ! -name "*_tb.sv" \
              ! -name "testbench.v" \
              ! -name "testbench.sv" \
              ! -name "*_tb1.v" \
              ! -name "*_tb2.v"
              
          )

          exit $status
